name: Lukkit
main: nz.co.jammehcow.lukkit.LukkitContainer
version: 2.1.2-paperfix

author: TheGamingMahi
authors: [jammehcow, AL_1, mathhulk, TheGamingMahi]

api-version: 1.13

commands:
  lukkit:
    description: The main command for Lukkit
    usage: /<command> [help|plugins|dev]
    permission: lukkit.command
    permission-message: You do not have permission to manage Lukkit.

permissions:
  lukkit.command:
    description: Give access to the /lukkit command.
    default: op
